# -*- coding: utf-8 -*-
win=False
coords_perso=[50,200]
game = True
depart=0.0
base_speed= 5
bullet_speed = 6
monstre_speed = 3
limit_monstre=10
percing=False
power_bullet = False
up = False
down = False
tab_bullet = []
tab_power = []
tab_monstre=[]
name_power=""
temps_power=0.0
in_power_use=False
affichage_power = False
vie = 4
frame=30
frame_power=60
score = 0
touche = False
back=True
affichage_verif = False
fond = None
avance=False
